### ISSUE TITLE
这个报错是什么原因呀

### ISSUE THREAD

**Issue by alvincna** [wahh159/damaiTickets#13]
Traceback (most recent call last):
  File "C:\Users\youwei\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\youwei\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\youwei\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\youwei\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\youwei\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(
  File "C:\Users\youwei\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 395, in request
    self.endheaders()
  File "C:\Users\youwei\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1322, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\youwei\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1081, in _send_output
    self.send(msg)
  File "C:\Users\youwei\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1025, in send
    self.connect()
  File "C:\Users\youwei\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 243, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "C:\Users\youwei\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002106053B8F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

**Comment by wahh159** [comment]
服务没开吧
